esphome:
  name: esp32-usb-hidx
  friendly_name: ESP32 USB HIDX

esp32:
  variant: esp32s3 #esp32p4
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_USB_HOST_ENABLE: y
      #CONFIG_USB_HOST_HCD_DWC_NUM_CHANNELS: "8" # S3 seems only can handle 3 devices: 1 USB HUB + 2 USB Devices 
      #CONFIG_ESP32S3_BROWNOUT_DET: "n"

external_components:
  #- source:
  #    type: local
  #    path: components
  - source: github://NonaSuomy/esphome@hidx-testing-001
    components: [usb_hidx]
    refresh: 0s

# Enable logging
logger:
  level: DEBUG
  hardware_uart: UART0
  logs:
    usb_hidx: DEBUG
    usb_host: DEBUG

web_server:
  version: 3
  port: 80

# USB Host configuration
usb_host:
  enable_hubs: true

# USB HIDX Component
usb_hidx:
  hub: true
  keyboard:
    device_id: keyboard_main
    layout: us  # Options: us, uk, de, fr, es
  mouse:
    device_id: mouse_main
  gamepad:
    device_id: gamepad_main
    type: generic

# Keyboard support
text_sensor:
  - platform: usb_hidx
    name: "Keyboard Input"
    type: keyboard

binary_sensor:
# Keyboard keys
  - platform: usb_hidx
    name: "Keyboard ESC"
    type: keyboard
    key: 0x29  # ESC key
  - platform: usb_hidx
    name: "Keyboard Enter"
    type: keyboard
    key: 0x28  # Enter key
# Mouse support
  - platform: usb_hidx
    name: "Mouse Left Button"
    type: mouse
    left_button: true
  - platform: usb_hidx
    name: "Mouse Right Button"
    type: mouse
    right_button: true
  - platform: usb_hidx
    name: "Mouse Middle Button"
    type: mouse
    middle_button: true
# Gamepad support
  - platform: usb_hidx
    name: "Gamepad A"
    type: gamepad
    button_a: true
  - platform: usb_hidx
    name: "Gamepad B"
    type: gamepad
    button_b: true

sensor:
  - platform: usb_hidx
    name: "Mouse X Movement"
    type: mouse
    x_delta: true
  - platform: usb_hidx
    name: "Mouse Y Movement"
    type: mouse
    y_delta: true
  - platform: usb_hidx
    name: "Mouse Wheel"
    type: mouse
    wheel: true
